/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 CesiumMan.gltf --transform 
Files: CesiumMan.gltf [51.95KB] > /Users/nivedithabp/Documents/try/CesiumMan-transformed.glb [103.87KB] (-100%)
*/
import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/CesiumMan-transformed.glb');
  // eslint-disable-next-line no-unused-vars
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Armature" rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
          <primitive object={nodes.Skeleton_torso_joint_1} />
        </group>
        <skinnedMesh
          name="Cesium_Man"
          geometry={nodes.Cesium_Man.geometry}
          material={materials['Cesium_Man-effect']}
          skeleton={nodes.Cesium_Man.skeleton}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/CesiumMan-transformed.glb');
